apiVersion : apps/v1
kind: Deployment
metadata:
  name: saikiranrkodotnetdemo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saikiranrkodotnetdemo
  template:
    metadata:
      labels:
        app: saikiranrkodotnetdemo 
    spec:
      containers:
        - name: dotnetdemo
          image: reg1122.azurecr.io/saikiranrkodotnetdemo
          ports:
          - containerPort: 5000
